language: python
python: 3.6

install:
    - pip install tox

env:
  # linters and coverage
  - TOX_ENV=pep8
  - TOX_ENV=coverage

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36-falcon1.0,py36-falcon1.1,py36-falcon1.2,py36-falcon1.3

    - python: 3.5
      env: TOX_ENV=py35-falcon1.0,py35-falcon1.1,py35-falcon1.2,py35-falcon1.3

    - python: 3.4
      env: TOX_ENV=py34-falcon1.0,py34-falcon1.1,py34-falcon1.2,py34-falcon1.3

    - python: 2.7
      env: TOX_ENV=py27-falcon1.0,py27-falcon1.1,py27-falcon1.2,py27-falcon1.3

    - python: 2.6
      env: TOX_ENV=py26-falcon1.0,py26-falcon1.1,py26-falcon1.2,py26-falcon1.3

script:
  - tox -e $TOX_ENV
